### ISSUE TITLE
Create separate class "VotingBooth" which holds voting logic

### ISSUE THREAD

**Issue by thomasvn** [deenaariff/Distributed-Value-Key-Store#5]
Nodes in any given state need to run this class. A few things it should take into account for:

1. Boolean variable to check whether a node has voted yet (keep track of whether the node has voted within this term yet)
2. What happens when a leader is requested to vote ??
3. In the case of an election timeout (time allotted to win the majority), re-run the election

**Comment by deenaariff** [comment]
Voting Functionality Encapsulated in RPC. Will not move voting functionality out of this.
